## Gradle Setting
org.gradle.jvmargs=-Xmx2048M
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
## Environment Properties
artifact_id=hajimaridisc-fabric
minecraft_version=1.20.1
fabric_version=0.92.6+1.20.1
loader_version=0.16.10
# Mod Properties
mod_id=hajimaridisc
mod_name=Hajimari No Kyoku Disc
mod_version=1.0.0-SNAPSHOT
maven_group=com.xunjang.mc
mod_authors=XunJang
mod_license=GNU LGPLv3
mod_description=
